### PR TITLE
Changes to add NIRSpec to the JWST instruments.

### PR DESCRIPTION
**Pull request by KevinVolkSTScI**
I have added the NIRSpec filters and made changes to the magnitude lists from the simulations.  I have also added the BOSZ model grid set.  I cannot go ahead and merge the changes, however.

### CODE REVIEW

**Comment by Johannes-Sahlmann** [comment]
I will look at this early next week. Apologies for the delay.

**Comment by KevinVolkSTScI** [comment]
Adding a unit test may be non-trivial, in that the main trust of the code is how it works interactively.  I will think about it and see what I come up with.  I simply test the code myself when I make the changes, but I do not (for example) verify that a given transformation say 2MASS J/Ks to NIRISS F115W/F200W remains the same as before.  It is a good idea to make something like this as a test of the code whether or not it can be run automatically.

**Comment by Johannes-Sahlmann** [comment]
I have scripts that call the converter programmatically. I can put something together for the NIRISS case.

**Comment by KevinVolkSTScI** [comment]
I can call the code from the command line.  But that does not exercise the interface.  But I would like to see an example of your script, although I think I know how to do this...

**Pull request merged**
